!function(d){function n(){}function l(d){function k(c){c.prototype.option||(c.prototype.option=function(a){d.isPlainObject(a)&&(this.options=d.extend(!0,this.options,a))})}function c(c,a){d.fn[c]=function(b){if("string"==typeof b){for(var k=g.call(arguments,1),B=0,e=this.length;e>B;B++){var m=d.data(this[B],c);if(m)if(d.isFunction(m[b])&&"_"!==b.charAt(0)){if(m=m[b].apply(m,k),void 0!==m)return m}else f("no such method '"+b+"' for "+c+" instance");else f("cannot call methods on "+c+" prior to initialization; attempted to call '"+
b+"'")}return this}return this.each(function(){var f=d.data(this,c);f?(f.option(b),f._init()):(f=new a(this,b),d.data(this,c,f))})}}if(d){var f="undefined"==typeof console?n:function(c){console.error(c)};return d.bridget=function(f,a){k(a);c(f,a)},d.bridget}}var g=Array.prototype.slice;"function"==typeof define&&define.amd?define("jquery-bridget/jquery.bridget",["jquery"],l):l("object"==typeof exports?require("jquery"):d.jQuery)}(window);
(function(d){function n(k){var c=d.event;return c.target=c.target||c.srcElement||k,c}var l=document.documentElement,g=function(){};l.addEventListener?g=function(d,c,f){d.addEventListener(c,f,!1)}:l.attachEvent&&(g=function(d,c,f){d[c+f]=f.handleEvent?function(){var c=n(d);f.handleEvent.call(f,c)}:function(){var c=n(d);f.call(d,c)};d.attachEvent("on"+c,d[c+f])});var p=function(){};l.removeEventListener?p=function(d,c,f){d.removeEventListener(c,f,!1)}:l.detachEvent&&(p=function(d,c,f){d.detachEvent("on"+
c,d[c+f]);try{delete d[c+f]}catch(u){d[c+f]=void 0}});l={bind:g,unbind:p};"function"==typeof define&&define.amd?define("eventie/eventie",l):"object"==typeof exports?module.exports=l:d.eventie=l})(this);
(function(d){function n(f){"function"==typeof f&&(n.isReady?f():c.push(f))}function l(c){c="readystatechange"===c.type&&"complete"!==k.readyState;n.isReady||c||g()}function g(){n.isReady=!0;for(var f=0,d=c.length;d>f;f++)(0,c[f])()}function p(c){return"complete"===k.readyState?g():(c.bind(k,"DOMContentLoaded",l),c.bind(k,"readystatechange",l),c.bind(d,"load",l)),n}var k=d.document,c=[];n.isReady=!1;"function"==typeof define&&define.amd?define("doc-ready/doc-ready",["eventie/eventie"],p):"object"==
typeof exports?module.exports=p(require("eventie")):d.docReady=p(d.eventie)})(window);
(function(){function d(){}function n(c,f){for(var d=c.length;d--;)if(c[d].listener===f)return d;return-1}function l(c){return function(){return this[c].apply(this,arguments)}}var g=d.prototype,p=this,k=p.EventEmitter;g.getListeners=function(c){var f,d,a=this._getEvents();if(c instanceof RegExp)for(d in f={},a)a.hasOwnProperty(d)&&c.test(d)&&(f[d]=a[d]);else f=a[c]||(a[c]=[]);return f};g.flattenListeners=function(c){var f,d=[];for(f=0;f<c.length;f+=1)d.push(c[f].listener);return d};g.getListenersAsObject=
function(c){var f,d=this.getListeners(c);return d instanceof Array&&(f={},f[c]=d),f||d};g.addListener=function(c,f){var d,a=this.getListenersAsObject(c),b="object"==typeof f;for(d in a)a.hasOwnProperty(d)&&-1===n(a[d],f)&&a[d].push(b?f:{listener:f,once:!1});return this};g.on=l("addListener");g.addOnceListener=function(c,f){return this.addListener(c,{listener:f,once:!0})};g.once=l("addOnceListener");g.defineEvent=function(c){return this.getListeners(c),this};g.defineEvents=function(c){for(var f=0;f<
c.length;f+=1)this.defineEvent(c[f]);return this};g.removeListener=function(c,f){var d,a,b=this.getListenersAsObject(c);for(a in b)b.hasOwnProperty(a)&&(d=n(b[a],f),-1!==d&&b[a].splice(d,1));return this};g.off=l("removeListener");g.addListeners=function(c,f){return this.manipulateListeners(!1,c,f)};g.removeListeners=function(c,f){return this.manipulateListeners(!0,c,f)};g.manipulateListeners=function(c,f,d){var a,b,t=c?this.removeListener:this.addListener;c=c?this.removeListeners:this.addListeners;
if("object"!=typeof f||f instanceof RegExp)for(a=d.length;a--;)t.call(this,f,d[a]);else for(a in f)f.hasOwnProperty(a)&&(b=f[a])&&("function"==typeof b?t.call(this,a,b):c.call(this,a,b));return this};g.removeEvent=function(c){var d,u=typeof c,a=this._getEvents();if("string"===u)delete a[c];else if(c instanceof RegExp)for(d in a)a.hasOwnProperty(d)&&c.test(d)&&delete a[d];else delete this._events;return this};g.removeAllListeners=l("removeEvent");g.emitEvent=function(c,d){var u,a,b,t,g=this.getListenersAsObject(c);
for(b in g)if(g.hasOwnProperty(b))for(a=g[b].length;a--;)u=g[b][a],!0===u.once&&this.removeListener(c,u.listener),t=u.listener.apply(this,d||[]),t===this._getOnceReturnValue()&&this.removeListener(c,u.listener);return this};g.trigger=l("emitEvent");g.emit=function(c){var d=Array.prototype.slice.call(arguments,1);return this.emitEvent(c,d)};g.setOnceReturnValue=function(c){return this._onceReturnValue=c,this};g._getOnceReturnValue=function(){return this.hasOwnProperty("_onceReturnValue")?this._onceReturnValue:
!0};g._getEvents=function(){return this._events||(this._events={})};d.noConflict=function(){return p.EventEmitter=k,d};"function"==typeof define&&define.amd?define("eventEmitter/EventEmitter",[],function(){return d}):"object"==typeof module&&module.exports?module.exports=d:p.EventEmitter=d}).call(this);
(function(d){function n(d){if(d){if("string"==typeof g[d])return d;d=d.charAt(0).toUpperCase()+d.slice(1);for(var k,c=0,f=l.length;f>c;c++)if(k=l[c]+d,"string"==typeof g[k])return k}}var l=["Webkit","Moz","ms","Ms","O"],g=document.documentElement.style;"function"==typeof define&&define.amd?define("get-style-property/get-style-property",[],function(){return n}):"object"==typeof exports?module.exports=n:d.getStyleProperty=n})(window);
(function(d){function n(c){var d=parseFloat(c);return-1===c.indexOf("%")&&!isNaN(d)&&d}function l(){}function g(c){function f(){if(!t){t=!0;var f=d.getComputedStyle;if(g=function(){var a=f?function(a){return f(a,null)}:function(a){return a.currentStyle};return function(b){b=a(b);return b||p("Style returned "+b+". Are you running this code in a hidden iframe on Firefox? See http://bit.ly/getsizebug1"),b}}(),a=c("boxSizing")){var e=document.createElement("div");e.style.width="200px";e.style.padding=
"1px 2px 3px 4px";e.style.borderStyle="solid";e.style.borderWidth="1px 2px 3px 4px";e.style[a]="border-box";var m=document.body||document.documentElement;m.appendChild(e);var I=g(e);b=200===n(I.width);m.removeChild(e)}}}var g,a,b,t=!1;return function(c){if(f(),"string"==typeof c&&(c=document.querySelector(c)),c&&"object"==typeof c&&c.nodeType){var e=g(c);if("none"===e.display){for(var m={width:0,height:0,innerWidth:0,innerHeight:0,outerWidth:0,outerHeight:0},e=0,t=k.length;t>e;e++)m[k[e]]=0;return m}m=
{};m.width=c.offsetWidth;m.height=c.offsetHeight;for(var t=m.isBorderBox=!(!a||!e[a]||"border-box"!==e[a]),y=0,q=k.length;q>y;y++){var l=k[y],h=e[l];var r=c,D=h;if(d.getComputedStyle||-1===D.indexOf("%"))h=D;else var h=r.style,H=h.left,E=r.runtimeStyle,C=E&&E.left,h=(C&&(E.left=r.currentStyle.left),h.left=D,D=h.pixelLeft,h.left=H,C&&(E.left=C),D);r=parseFloat(h);m[l]=isNaN(r)?0:r}c=m.paddingLeft+m.paddingRight;y=m.paddingTop+m.paddingBottom;q=m.marginLeft+m.marginRight;l=m.marginTop+m.marginBottom;
r=m.borderLeftWidth+m.borderRightWidth;D=m.borderTopWidth+m.borderBottomWidth;t=t&&b;h=n(e.width);!1!==h&&(m.width=h+(t?0:c+r));e=n(e.height);return!1!==e&&(m.height=e+(t?0:y+D)),m.innerWidth=m.width-(c+r),m.innerHeight=m.height-(y+D),m.outerWidth=m.width+q,m.outerHeight=m.height+l,m}}}var p="undefined"==typeof console?l:function(c){console.error(c)},k="paddingLeft paddingRight paddingTop paddingBottom marginLeft marginRight marginTop marginBottom borderLeftWidth borderRightWidth borderTopWidth borderBottomWidth".split(" ");
"function"==typeof define&&define.amd?define("get-size/get-size",["get-style-property/get-style-property"],g):"object"==typeof exports?module.exports=g(require("desandro-get-style-property")):d.getSize=g(d.getStyleProperty)})(window);
(function(d){function n(c,d){return c[k](d)}function l(c,d){c.parentNode||document.createDocumentFragment().appendChild(c);for(var a=c.parentNode.querySelectorAll(d),b=0,g=a.length;g>b;b++)if(a[b]===c)return!0;return!1}function g(c,d){c.parentNode||document.createDocumentFragment().appendChild(c);return n(c,d)}var p,k=function(){if(d.matchesSelector)return"matchesSelector";for(var c=["webkit","moz","ms","o"],g=0,a=c.length;a>g;g++){var b=c[g]+"MatchesSelector";if(d[b])return b}}();if(k){var c=document.createElement("div");
p=n(c,"div")?n:g}else p=l;"function"==typeof define&&define.amd?define("matches-selector/matches-selector",[],function(){return p}):"object"==typeof exports?module.exports=p:window.matchesSelector=p})(Element.prototype);
(function(d){function n(c,d){for(var g in d)c[g]=d[g];return c}function l(c){return c.replace(/([A-Z])/g,function(c){return"-"+c.toLowerCase()})}function g(c,d,g){function a(a,b){a&&(this.element=a,this.layout=b,this.position={x:0,y:0},this._create())}var b=g("transition"),t=g("transform"),p=b&&t,e=!!g("perspective"),m={WebkitTransition:"webkitTransitionEnd",MozTransition:"transitionend",OTransition:"otransitionend",transition:"transitionend"}[b],I=["transform","transition","transitionDuration","transitionProperty"],
y=function(){for(var a={},b=0,c=I.length;c>b;b++){var d=I[b],e=g(d);e&&e!==d&&(a[d]=e)}return a}();n(a.prototype,c.prototype);a.prototype._create=function(){this._transn={ingProperties:{},clean:{},onEnd:{}};this.css({position:"absolute"})};a.prototype.handleEvent=function(a){var b="on"+a.type;this[b]&&this[b](a)};a.prototype.getSize=function(){this.size=d(this.element)};a.prototype.css=function(a){var b=this.element.style,c;for(c in a)b[y[c]||c]=a[c]};a.prototype.getPosition=function(){var a=k(this.element),
b=this.layout.options,c=b.isOriginLeft,b=b.isOriginTop,d=parseInt(a[c?"left":"right"],10),a=parseInt(a[b?"top":"bottom"],10),d=isNaN(d)?0:d,a=isNaN(a)?0:a,e=this.layout.size,d=d-(c?e.paddingLeft:e.paddingRight),a=a-(b?e.paddingTop:e.paddingBottom);this.position.x=d;this.position.y=a};a.prototype.layoutPosition=function(){var a=this.layout.size,b=this.layout.options,c={};b.isOriginLeft?(c.left=this.position.x+a.paddingLeft+"px",c.right=""):(c.right=this.position.x+a.paddingRight+"px",c.left="");b.isOriginTop?
(c.top=this.position.y+a.paddingTop+"px",c.bottom=""):(c.bottom=this.position.y+a.paddingBottom+"px",c.top="");this.css(c);this.emitEvent("layout",[this])};var q=e?function(a,b){return"translate3d("+a+"px, "+b+"px, 0)"}:function(a,b){return"translate("+a+"px, "+b+"px)"};a.prototype._transitionTo=function(a,b){this.getPosition();var c=this.position.x,d=this.position.y,e=parseInt(a,10),f=parseInt(b,10),e=e===this.position.x&&f===this.position.y;if(this.setPosition(a,b),e&&!this.isTransitioning)return void this.layoutPosition();
c=a-c;d=b-d;e={};f=this.layout.options;c=f.isOriginLeft?c:-c;d=f.isOriginTop?d:-d;e.transform=q(c,d);this.transition({to:e,onTransitionEnd:{transform:this.layoutPosition},isCleaning:!0})};a.prototype.goTo=function(a,b){this.setPosition(a,b);this.layoutPosition()};a.prototype.moveTo=p?a.prototype._transitionTo:a.prototype.goTo;a.prototype.setPosition=function(a,b){this.position.x=parseInt(a,10);this.position.y=parseInt(b,10)};a.prototype._nonTransition=function(a){this.css(a.to);a.isCleaning&&this._removeStyles(a.to);
for(var b in a.onTransitionEnd)a.onTransitionEnd[b].call(this)};a.prototype._transition=function(a){if(!parseFloat(this.layout.options.transitionDuration))return void this._nonTransition(a);var b=this._transn,c;for(c in a.onTransitionEnd)b.onEnd[c]=a.onTransitionEnd[c];for(c in a.to)b.ingProperties[c]=!0,a.isCleaning&&(b.clean[c]=!0);a.from&&this.css(a.from);this.enableTransition(a.to);this.css(a.to);this.isTransitioning=!0};var G=t&&l(t)+",opacity";a.prototype.enableTransition=function(){this.isTransitioning||
(this.css({transitionProperty:G,transitionDuration:this.layout.options.transitionDuration}),this.element.addEventListener(m,this,!1))};a.prototype.transition=a.prototype[b?"_transition":"_nonTransition"];a.prototype.onwebkitTransitionEnd=function(a){this.ontransitionend(a)};a.prototype.onotransitionend=function(a){this.ontransitionend(a)};var h={"-webkit-transform":"transform","-moz-transform":"transform","-o-transform":"transform"};a.prototype.ontransitionend=function(a){if(a.target===this.element){var b=
this._transn,c=h[a.propertyName]||a.propertyName;delete b.ingProperties[c];var d;a:{d=b.ingProperties;for(var e in d){d=!1;break a}d=!0}if(d&&this.disableTransition(),c in b.clean&&(this.element.style[a.propertyName]="",delete b.clean[c]),c in b.onEnd)b.onEnd[c].call(this),delete b.onEnd[c];this.emitEvent("transitionEnd",[this])}};a.prototype.disableTransition=function(){this.removeTransitionStyles();this.element.removeEventListener(m,this,!1);this.isTransitioning=!1};a.prototype._removeStyles=function(a){var b=
{},c;for(c in a)b[c]="";this.css(b)};var r={transitionProperty:"",transitionDuration:""};return a.prototype.removeTransitionStyles=function(){this.css(r)},a.prototype.removeElem=function(){this.element.parentNode.removeChild(this.element);this.emitEvent("remove",[this])},a.prototype.remove=function(){if(!b||!parseFloat(this.layout.options.transitionDuration))return void this.removeElem();var a=this;this.on("transitionEnd",function(){return a.removeElem(),!0});this.hide()},a.prototype.reveal=function(){delete this.isHidden;
this.css({display:""});var a=this.layout.options;this.transition({from:a.hiddenStyle,to:a.visibleStyle,isCleaning:!0})},a.prototype.hide=function(){this.isHidden=!0;this.css({display:""});var a=this.layout.options;this.transition({from:a.visibleStyle,to:a.hiddenStyle,isCleaning:!0,onTransitionEnd:{opacity:function(){this.isHidden&&this.css({display:"none"})}}})},a.prototype.destroy=function(){this.css({position:"",left:"",right:"",top:"",bottom:"",transition:"",transform:""})},a}var p=d.getComputedStyle,
k=p?function(c){return p(c,null)}:function(c){return c.currentStyle};"function"==typeof define&&define.amd?define("outlayer/item",["eventEmitter/EventEmitter","get-size/get-size","get-style-property/get-style-property"],g):"object"==typeof exports?module.exports=g(require("wolfy87-eventemitter"),require("get-size"),require("desandro-get-style-property")):(d.Outlayer={},d.Outlayer.Item=g(d.EventEmitter,d.getSize,d.getStyleProperty))})(window);
(function(d){function n(a,b){for(var c in b)a[c]=b[c];return a}function l(a){var c=[];if("[object Array]"===b.call(a))c=a;else if(a&&"number"==typeof a.length)for(var d=0,f=a.length;f>d;d++)c.push(a[d]);else c.push(a);return c}function g(a,b){var c=B(b,a);-1!==c&&b.splice(c,1)}function p(a){return a.replace(/(.)([A-Z])/g,function(a,b,c){return b+"-"+c}).toLowerCase()}function k(b,m,k,y,q,G){function h(a,b){if("string"==typeof a&&(a=c.querySelector(a)),!a||!t(a))return void(f&&f.error("Bad "+this.constructor.namespace+
" element: "+a));this.element=a;this.options=n({},this.constructor.defaults);this.option(b);var d=++r;this.element.outlayerGUID=d;B[d]=this;this._create();this.options.isInitLayout&&this.layout()}var r=0,B={};return h.namespace="outlayer",h.Item=G,h.defaults={containerStyle:{position:"relative"},isInitLayout:!0,isOriginLeft:!0,isOriginTop:!0,isResizeBound:!0,isResizingContainer:!0,transitionDuration:"0.4s",hiddenStyle:{opacity:0,transform:"scale(0.001)"},visibleStyle:{opacity:1,transform:"scale(1)"}},
n(h.prototype,k.prototype),h.prototype.option=function(a){n(this.options,a)},h.prototype._create=function(){this.reloadItems();this.stamps=[];this.stamp(this.options.stamp);n(this.element.style,this.options.containerStyle);this.options.isResizeBound&&this.bindResize()},h.prototype.reloadItems=function(){this.items=this._itemize(this.element.children)},h.prototype._itemize=function(a){a=this._filterFindItemElements(a);for(var b=this.constructor.Item,c=[],d=0,e=a.length;e>d;d++){var f=new b(a[d],this);
c.push(f)}return c},h.prototype._filterFindItemElements=function(a){a=l(a);for(var b=this.options.itemSelector,c=[],d=0,e=a.length;e>d;d++){var f=a[d];if(t(f))if(b){q(f,b)&&c.push(f);for(var f=f.querySelectorAll(b),h=0,g=f.length;g>h;h++)c.push(f[h])}else c.push(f)}return c},h.prototype.getItemElements=function(){for(var a=[],b=0,c=this.items.length;c>b;b++)a.push(this.items[b].element);return a},h.prototype.layout=function(){this._resetLayout();this._manageStamps();this.layoutItems(this.items,void 0!==
this.options.isLayoutInstant?this.options.isLayoutInstant:!this._isLayoutInited);this._isLayoutInited=!0},h.prototype._init=h.prototype.layout,h.prototype._resetLayout=function(){this.getSize()},h.prototype.getSize=function(){this.size=y(this.element)},h.prototype._getMeasurement=function(a,b){var c,d=this.options[a];d?("string"==typeof d?c=this.element.querySelector(d):t(d)&&(c=d),this[a]=c?y(c)[b]:d):this[a]=0},h.prototype.layoutItems=function(a,b){a=this._getItemsForLayout(a);this._layoutItems(a,
b);this._postLayout()},h.prototype._getItemsForLayout=function(a){for(var b=[],c=0,d=a.length;d>c;c++){var e=a[c];e.isIgnored||b.push(e)}return b},h.prototype._layoutItems=function(a,b){function c(){d.emitEvent("layoutComplete",[d,a])}var d=this;if(!a||!a.length)return void c();this._itemsOn(a,"layout",c);for(var e=[],f=0,h=a.length;h>f;f++){var g=a[f],m=this._getItemLayoutPosition(g);m.item=g;m.isInstant=b||g.isLayoutInstant;e.push(m)}this._processLayoutQueue(e)},h.prototype._getItemLayoutPosition=
function(){return{x:0,y:0}},h.prototype._processLayoutQueue=function(a){for(var b=0,c=a.length;c>b;b++){var d=a[b];this._positionItem(d.item,d.x,d.y,d.isInstant)}},h.prototype._positionItem=function(a,b,c,d){d?a.goTo(b,c):a.moveTo(b,c)},h.prototype._postLayout=function(){this.resizeContainer()},h.prototype.resizeContainer=function(){if(this.options.isResizingContainer){var a=this._getContainerSize();a&&(this._setContainerMeasure(a.width,!0),this._setContainerMeasure(a.height,!1))}},h.prototype._getContainerSize=
a,h.prototype._setContainerMeasure=function(a,b){if(void 0!==a){var c=this.size;c.isBorderBox&&(a+=b?c.paddingLeft+c.paddingRight+c.borderLeftWidth+c.borderRightWidth:c.paddingBottom+c.paddingTop+c.borderTopWidth+c.borderBottomWidth);a=Math.max(a,0);this.element.style[b?"width":"height"]=a+"px"}},h.prototype._itemsOn=function(a,b,c){function d(){return e++,e===f&&c.call(h),!0}for(var e=0,f=a.length,h=this,g=0,m=a.length;m>g;g++)a[g].on(b,d)},h.prototype.ignore=function(a){(a=this.getItem(a))&&(a.isIgnored=
!0)},h.prototype.unignore=function(a){(a=this.getItem(a))&&delete a.isIgnored},h.prototype.stamp=function(a){if(a=this._find(a)){this.stamps=this.stamps.concat(a);for(var b=0,c=a.length;c>b;b++)this.ignore(a[b])}},h.prototype.unstamp=function(a){if(a=this._find(a))for(var b=0,c=a.length;c>b;b++){var d=a[b];g(d,this.stamps);this.unignore(d)}},h.prototype._find=function(a){return a?("string"==typeof a&&(a=this.element.querySelectorAll(a)),l(a)):void 0},h.prototype._manageStamps=function(){if(this.stamps&&
this.stamps.length){this._getBoundingRect();for(var a=0,b=this.stamps.length;b>a;a++)this._manageStamp(this.stamps[a])}},h.prototype._getBoundingRect=function(){var a=this.element.getBoundingClientRect(),b=this.size;this._boundingRect={left:a.left+b.paddingLeft+b.borderLeftWidth,top:a.top+b.paddingTop+b.borderTopWidth,right:a.right-(b.paddingRight+b.borderRightWidth),bottom:a.bottom-(b.paddingBottom+b.borderBottomWidth)}},h.prototype._manageStamp=a,h.prototype._getElementOffset=function(a){var b=
a.getBoundingClientRect(),c=this._boundingRect;a=y(a);return{left:b.left-c.left-a.marginLeft,top:b.top-c.top-a.marginTop,right:c.right-b.right-a.marginRight,bottom:c.bottom-b.bottom-a.marginBottom}},h.prototype.handleEvent=function(a){var b="on"+a.type;this[b]&&this[b](a)},h.prototype.bindResize=function(){this.isResizeBound||(b.bind(d,"resize",this),this.isResizeBound=!0)},h.prototype.unbindResize=function(){this.isResizeBound&&b.unbind(d,"resize",this);this.isResizeBound=!1},h.prototype.onresize=
function(){this.resizeTimeout&&clearTimeout(this.resizeTimeout);var a=this;this.resizeTimeout=setTimeout(function(){a.resize();delete a.resizeTimeout},100)},h.prototype.resize=function(){this.isResizeBound&&this.needsResizeLayout()&&this.layout()},h.prototype.needsResizeLayout=function(){var a=y(this.element);return this.size&&a&&a.innerWidth!==this.size.innerWidth},h.prototype.addItems=function(a){a=this._itemize(a);return a.length&&(this.items=this.items.concat(a)),a},h.prototype.appended=function(a){a=
this.addItems(a);a.length&&(this.layoutItems(a,!0),this.reveal(a))},h.prototype.prepended=function(a){a=this._itemize(a);if(a.length){var b=this.items.slice(0);this.items=a.concat(b);this._resetLayout();this._manageStamps();this.layoutItems(a,!0);this.reveal(a);this.layoutItems(b)}},h.prototype.reveal=function(a){var b=a&&a.length;if(b)for(var c=0;b>c;c++)a[c].reveal()},h.prototype.hide=function(a){var b=a&&a.length;if(b)for(var c=0;b>c;c++)a[c].hide()},h.prototype.getItem=function(a){for(var b=0,
c=this.items.length;c>b;b++){var d=this.items[b];if(d.element===a)return d}},h.prototype.getItems=function(a){if(a&&a.length){for(var b=[],c=0,d=a.length;d>c;c++){var e=this.getItem(a[c]);e&&b.push(e)}return b}},h.prototype.remove=function(a){a=l(a);var b=this.getItems(a);if(b&&b.length){this._itemsOn(b,"remove",function(){this.emitEvent("removeComplete",[this,b])});a=0;for(var c=b.length;c>a;a++){var d=b[a];d.remove();g(d,this.items)}}},h.prototype.destroy=function(){var a=this.element.style;a.height=
"";a.position="";a.width="";for(var a=0,b=this.items.length;b>a;a++)this.items[a].destroy();this.unbindResize();delete B[this.element.outlayerGUID];delete this.element.outlayerGUID;u&&u.removeData(this.element,this.constructor.namespace)},h.data=function(a){return(a=a&&a.outlayerGUID)&&B[a]},h.create=function(a,b){function d(){h.apply(this,arguments)}return Object.create?d.prototype=Object.create(h.prototype):n(d.prototype,h.prototype),d.prototype.constructor=d,d.defaults=n({},h.defaults),n(d.defaults,
b),d.prototype.settings={},d.namespace=a,d.data=h.data,d.Item=function(){G.apply(this,arguments)},d.Item.prototype=new G,m(function(){for(var b=p(a),e=c.querySelectorAll(".js-"+b),b="data-"+b+"-options",h=0,g=e.length;g>h;h++){var m,t=e[h],k=t.getAttribute(b);try{m=k&&JSON.parse(k)}catch(q){f&&f.error("Error parsing "+b+" on "+t.nodeName.toLowerCase()+(t.id?"#"+t.id:"")+": "+q);continue}k=new d(t,m);u&&u.data(t,a,k)}}),u&&u.bridget&&u.bridget(a,d),d},h.Item=G,h}var c=d.document,f=d.console,u=d.jQuery,
a=function(){},b=Object.prototype.toString,t="function"==typeof HTMLElement||"object"==typeof HTMLElement?function(a){return a instanceof HTMLElement}:function(a){return a&&"object"==typeof a&&1===a.nodeType&&"string"==typeof a.nodeName},B=Array.prototype.indexOf?function(a,b){return a.indexOf(b)}:function(a,b){for(var c=0,d=a.length;d>c;c++)if(a[c]===b)return c;return-1};"function"==typeof define&&define.amd?define("outlayer/outlayer","eventie/eventie doc-ready/doc-ready eventEmitter/EventEmitter get-size/get-size matches-selector/matches-selector ./item".split(" "),
k):"object"==typeof exports?module.exports=k(require("eventie"),require("doc-ready"),require("wolfy87-eventemitter"),require("get-size"),require("desandro-matches-selector"),require("./item")):d.Outlayer=k(d.eventie,d.docReady,d.EventEmitter,d.getSize,d.matchesSelector,d.Outlayer.Item)})(window);
(function(d){function n(d,n){var k=d.create("masonry");return k.prototype._resetLayout=function(){this.getSize();this._getMeasurement("columnWidth","outerWidth");this._getMeasurement("gutter","outerWidth");this.measureColumns();var c=this.cols;for(this.colYs=[];c--;)this.colYs.push(0);this.maxY=0},k.prototype.measureColumns=function(){if(this.getContainerWidth(),!this.columnWidth){var c=this.items[0];this.columnWidth=(c=c&&c.element)&&n(c).outerWidth||this.containerWidth}this.columnWidth+=this.gutter;
this.cols=Math.floor((this.containerWidth+this.gutter)/this.columnWidth);this.cols=Math.max(this.cols,1)},k.prototype.getContainerWidth=function(){var c=n(this.options.isFitWidth?this.element.parentNode:this.element);this.containerWidth=c&&c.innerWidth},k.prototype._getItemLayoutPosition=function(c){c.getSize();var d=c.size.outerWidth%this.columnWidth,d=Math[d&&1>d?"round":"ceil"](c.size.outerWidth/this.columnWidth),d=Math.min(d,this.cols),g=this._getColGroup(d),a=Math.min.apply(Math,g),d=l(g,a),
b={x:this.columnWidth*d,y:a};c=a+c.size.outerHeight;g=this.cols+1-g.length;for(a=0;g>a;a++)this.colYs[d+a]=c;return b},k.prototype._getColGroup=function(c){if(2>c)return this.colYs;for(var d=[],g=this.cols+1-c,a=0;g>a;a++){var b=this.colYs.slice(a,a+c);d[a]=Math.max.apply(Math,b)}return d},k.prototype._manageStamp=function(c){var d=n(c),g=this._getElementOffset(c);c=this.options.isOriginLeft?g.left:g.right;var a=c+d.outerWidth,b=Math.floor(c/this.columnWidth),b=Math.max(0,b);c=Math.floor(a/this.columnWidth);
c-=a%this.columnWidth?0:1;c=Math.min(this.cols-1,c);d=(this.options.isOriginTop?g.top:g.bottom)+d.outerHeight;for(g=b;c>=g;g++)this.colYs[g]=Math.max(d,this.colYs[g])},k.prototype._getContainerSize=function(){this.maxY=Math.max.apply(Math,this.colYs);var c={height:this.maxY};return this.options.isFitWidth&&(c.width=this._getContainerFitWidth()),c},k.prototype._getContainerFitWidth=function(){for(var c=0,d=this.cols;--d&&0===this.colYs[d];)c++;return(this.cols-c)*this.columnWidth-this.gutter},k.prototype.needsResizeLayout=
function(){var c=this.containerWidth;return this.getContainerWidth(),c!==this.containerWidth},k}var l=Array.prototype.indexOf?function(d,n){return d.indexOf(n)}:function(d,n){for(var k=0,c=d.length;c>k;k++)if(d[k]===n)return k;return-1};"function"==typeof define&&define.amd?define(["outlayer/outlayer","get-size/get-size"],n):"object"==typeof exports?module.exports=n(require("outlayer"),require("get-size")):d.Masonry=n(d.Outlayer,d.getSize)})(window);
$(window).load(function(){$(".modul.news .cell .items").masonry({gutter:0,itemSelector:".news-segment",singleMode:!0})});
(function(d,n,l){function g(a,b){this.bodyOverflowX;this.callbacks={hide:[],show:[]};this.checkInterval=null;this.Content;this.$el=d(a);this.$elProxy;this.elProxyPosition;this.enabled=!0;this.options=d.extend({},c,b);this.mouseIsOverProxy=!1;this.namespace="tooltipster-"+Math.round(1E5*Math.random());this.Status="hidden";this.timerShow=this.timerHide=null;this.$tooltip;this.options.iconTheme=this.options.iconTheme.replace(".","");this.options.theme=this.options.theme.replace(".","");this._init()}
function p(a,b){var c=!0;d.each(a,function(d,e){if("undefined"===typeof b[d]||a[d]!==b[d])return c=!1});return c}function k(){var a=(l.body||l.documentElement).style,b="transition";if("string"==typeof a[b])return!0;v=["Moz","Webkit","Khtml","O","ms"];for(var b=b.charAt(0).toUpperCase()+b.substr(1),c=0;c<v.length;c++)if("string"==typeof a[v[c]+b])return!0;return!1}var c={animation:"fade",arrow:!0,arrowColor:"",autoClose:!0,content:null,contentAsHTML:!1,contentCloning:!0,debug:!0,delay:200,minWidth:0,
maxWidth:null,functionInit:function(a,b){},functionBefore:function(a,b){b()},functionReady:function(a,b){},functionAfter:function(a){},hideOnClick:!1,icon:"(?)",iconCloning:!0,iconDesktop:!1,iconTouch:!1,iconTheme:"tooltipster-icon",interactive:!1,interactiveTolerance:350,multiple:!1,offsetX:0,offsetY:0,onlyOne:!1,position:"top",positionTracker:!1,positionTrackerCallback:function(a){"hover"==this.option("trigger")&&this.option("autoClose")&&this.hide()},restoration:"current",speed:350,timer:0,theme:"tooltipster-default",
touchDevices:!0,trigger:"hover",updateAnimation:!0};g.prototype={_init:function(){var a=this;if(l.querySelector){var b=null;void 0===a.$el.data("tooltipster-initialTitle")&&(b=a.$el.attr("title"),void 0===b&&(b=null),a.$el.data("tooltipster-initialTitle",b));null!==a.options.content?a._content_set(a.options.content):a._content_set(b);b=a.options.functionInit.call(a.$el,a.$el,a.Content);"undefined"!==typeof b&&a._content_set(b);a.$el.removeAttr("title").addClass("tooltipstered");!f&&a.options.iconDesktop||
f&&a.options.iconTouch?("string"===typeof a.options.icon?(a.$elProxy=d('<span class="'+a.options.iconTheme+'"></span>'),a.$elProxy.text(a.options.icon)):a.$elProxy=a.options.iconCloning?a.options.icon.clone(!0):a.options.icon,a.$elProxy.insertAfter(a.$el)):a.$elProxy=a.$el;if("hover"==a.options.trigger){if(a.$elProxy.on("mouseenter."+a.namespace,function(){if(u||!f||a.options.touchDevices)a.mouseIsOverProxy=!0,a._show()}).on("mouseleave."+a.namespace,function(){if(u||!f||a.options.touchDevices)a.mouseIsOverProxy=
!1}),f&&a.options.touchDevices)a.$elProxy.on("touchstart."+a.namespace,function(){a._showNow()})}else if("click"==a.options.trigger)a.$elProxy.on("click."+a.namespace,function(){(u||!f||a.options.touchDevices)&&a._show()})}},_show:function(){var a=this;"shown"!=a.Status&&"appearing"!=a.Status&&(a.options.delay?a.timerShow=setTimeout(function(){("click"==a.options.trigger||"hover"==a.options.trigger&&a.mouseIsOverProxy)&&a._showNow()},a.options.delay):a._showNow())},_showNow:function(a){var b=this;
b.options.functionBefore.call(b.$el,b.$el,function(){if(b.enabled&&null!==b.Content){a&&b.callbacks.show.push(a);b.callbacks.hide=[];clearTimeout(b.timerShow);b.timerShow=null;clearTimeout(b.timerHide);b.timerHide=null;b.options.onlyOne&&d(".tooltipstered").not(b.$el).each(function(a,b){var c=d(b),e=c.data("tooltipster-ns");d.each(e,function(a,b){var d=c.data(b),e=d.status(),f=d.option("autoClose");"hidden"!==e&&"disappearing"!==e&&f&&d.hide()})});var c=function(){b.Status="shown";d.each(b.callbacks.show,
function(a,c){c.call(b.$el)});b.callbacks.show=[]};if("hidden"!==b.Status){var g=0;"disappearing"===b.Status?(b.Status="appearing",k()?(b.$tooltip.clearQueue().removeClass("tooltipster-dying").addClass("tooltipster-"+b.options.animation+"-show"),0<b.options.speed&&b.$tooltip.delay(b.options.speed),b.$tooltip.queue(c)):b.$tooltip.stop().fadeIn(c)):"shown"===b.Status&&c()}else{b.Status="appearing";g=b.options.speed;b.bodyOverflowX=d("body").css("overflow-x");d("body").css("overflow-x","hidden");var e=
"tooltipster-"+b.options.animation,m="-webkit-transition-duration: "+b.options.speed+"ms; -webkit-animation-duration: "+b.options.speed+"ms; -moz-transition-duration: "+b.options.speed+"ms; -moz-animation-duration: "+b.options.speed+"ms; -o-transition-duration: "+b.options.speed+"ms; -o-animation-duration: "+b.options.speed+"ms; -ms-transition-duration: "+b.options.speed+"ms; -ms-animation-duration: "+b.options.speed+"ms; transition-duration: "+b.options.speed+"ms; animation-duration: "+b.options.speed+
"ms;",l=b.options.minWidth?"min-width:"+Math.round(b.options.minWidth)+"px;":"",y=b.options.maxWidth?"max-width:"+Math.round(b.options.maxWidth)+"px;":"";b.$tooltip=d('<div class="tooltipster-base '+b.options.theme+'" style="'+l+" "+y+" "+(b.options.interactive?"pointer-events: auto;":"")+" "+m+'"><div class="tooltipster-content"></div></div>');k()&&b.$tooltip.addClass(e);b._content_insert();b.$tooltip.appendTo("body");b.reposition();b.options.functionReady.call(b.$el,b.$el,b.$tooltip);k()?(b.$tooltip.addClass(e+
"-show"),0<b.options.speed&&b.$tooltip.delay(b.options.speed),b.$tooltip.queue(c)):b.$tooltip.css("display","none").fadeIn(b.options.speed,c);b._interval_set();d(n).on("scroll."+b.namespace+" resize."+b.namespace,function(){b.reposition()});if(b.options.autoClose)if(d("body").off("."+b.namespace),"hover"==b.options.trigger){f&&setTimeout(function(){d("body").on("touchstart."+b.namespace,function(){b.hide()})},0);if(b.options.interactive){if(f)b.$tooltip.on("touchstart."+b.namespace,function(a){a.stopPropagation()});
var q=null;b.$elProxy.add(b.$tooltip).on("mouseleave."+b.namespace+"-autoClose",function(){clearTimeout(q);q=setTimeout(function(){b.hide()},b.options.interactiveTolerance)}).on("mouseenter."+b.namespace+"-autoClose",function(){clearTimeout(q)})}else b.$elProxy.on("mouseleave."+b.namespace+"-autoClose",function(){b.hide()});if(b.options.hideOnClick)b.$elProxy.on("click."+b.namespace+"-autoClose",function(){b.hide()})}else if("click"==b.options.trigger&&(setTimeout(function(){d("body").on("click."+
b.namespace+" touchstart."+b.namespace,function(){b.hide()})},0),b.options.interactive))b.$tooltip.on("click."+b.namespace+" touchstart."+b.namespace,function(a){a.stopPropagation()})}0<b.options.timer&&(b.timerHide=setTimeout(function(){b.timerHide=null;b.hide()},b.options.timer+g))}})},_interval_set:function(){var a=this;a.checkInterval=setInterval(function(){if(0===d("body").find(a.$el).length||0===d("body").find(a.$elProxy).length||"hidden"==a.Status||0===d("body").find(a.$tooltip).length)"shown"!=
a.Status&&"appearing"!=a.Status||a.hide(),a._interval_cancel();else if(a.options.positionTracker){var b=a._repositionInfo(a.$elProxy),c=!1;p(b.dimension,a.elProxyPosition.dimension)&&("fixed"===a.$elProxy.css("position")?p(b.position,a.elProxyPosition.position)&&(c=!0):p(b.offset,a.elProxyPosition.offset)&&(c=!0));c||(a.reposition(),a.options.positionTrackerCallback.call(a,a.$el))}},200)},_interval_cancel:function(){clearInterval(this.checkInterval);this.checkInterval=null},_content_set:function(a){"object"===
typeof a&&null!==a&&this.options.contentCloning&&(a=a.clone(!0));this.Content=a},_content_insert:function(){var a=this.$tooltip.find(".tooltipster-content");"string"!==typeof this.Content||this.options.contentAsHTML?a.empty().append(this.Content):a.text(this.Content)},_update:function(a){var b=this;b._content_set(a);null!==b.Content?"hidden"!==b.Status&&(b._content_insert(),b.reposition(),b.options.updateAnimation&&(k()?(b.$tooltip.css({width:"","-webkit-transition":"all "+b.options.speed+"ms, width 0ms, height 0ms, left 0ms, top 0ms",
"-moz-transition":"all "+b.options.speed+"ms, width 0ms, height 0ms, left 0ms, top 0ms","-o-transition":"all "+b.options.speed+"ms, width 0ms, height 0ms, left 0ms, top 0ms","-ms-transition":"all "+b.options.speed+"ms, width 0ms, height 0ms, left 0ms, top 0ms",transition:"all "+b.options.speed+"ms, width 0ms, height 0ms, left 0ms, top 0ms"}).addClass("tooltipster-content-changing"),setTimeout(function(){"hidden"!=b.Status&&(b.$tooltip.removeClass("tooltipster-content-changing"),setTimeout(function(){"hidden"!==
b.Status&&b.$tooltip.css({"-webkit-transition":b.options.speed+"ms","-moz-transition":b.options.speed+"ms","-o-transition":b.options.speed+"ms","-ms-transition":b.options.speed+"ms",transition:b.options.speed+"ms"})},b.options.speed))},b.options.speed)):b.$tooltip.fadeTo(b.options.speed,.5,function(){"hidden"!=b.Status&&b.$tooltip.fadeTo(b.options.speed,1)}))):b.hide()},_repositionInfo:function(a){return{dimension:{height:a.outerHeight(!1),width:a.outerWidth(!1)},offset:a.offset(),position:{left:parseInt(a.css("left")),
top:parseInt(a.css("top"))}}},hide:function(a){var b=this;a&&b.callbacks.hide.push(a);b.callbacks.show=[];clearTimeout(b.timerShow);b.timerShow=null;clearTimeout(b.timerHide);b.timerHide=null;var c=function(){d.each(b.callbacks.hide,function(a,c){c.call(b.$el)});b.callbacks.hide=[]};"shown"==b.Status||"appearing"==b.Status?(b.Status="disappearing",a=function(){b.Status="hidden";"object"==typeof b.Content&&null!==b.Content&&b.Content.detach();b.$tooltip.remove();b.$tooltip=null;d(n).off("."+b.namespace);
d("body").off("."+b.namespace).css("overflow-x",b.bodyOverflowX);d("body").off("."+b.namespace);b.$elProxy.off("."+b.namespace+"-autoClose");b.options.functionAfter.call(b.$el,b.$el);c()},k()?(b.$tooltip.clearQueue().removeClass("tooltipster-"+b.options.animation+"-show").addClass("tooltipster-dying"),0<b.options.speed&&b.$tooltip.delay(b.options.speed),b.$tooltip.queue(a)):b.$tooltip.stop().fadeOut(b.options.speed,a)):"hidden"==b.Status&&c();return b},show:function(a){this._showNow(a);return this},
update:function(a){return this.content(a)},content:function(a){if("undefined"===typeof a)return this.Content;this._update(a);return this},reposition:function(){if(0!==d("body").find(this.$tooltip).length){var a=function(a,b){0>e.offset.top-d(n).scrollTop()-k-z-12&&-1<b.indexOf("top")&&(x=a);e.offset.top+e.dimension.height+k+12+z>d(n).scrollTop()+d(n).height()&&-1<b.indexOf("bottom")&&(x=a,A=e.offset.top-k-z-12)},b=function(){var a=d(n).scrollLeft();0>w-a&&(c=w-a,w=a);w+g-a>f&&(c=w-(f+a-g),w=f+a-g)};
this.$tooltip.css("width","");this.elProxyPosition=this._repositionInfo(this.$elProxy);var c=null,f=d(n).width(),e=this.elProxyPosition,g=this.$tooltip.outerWidth(!1);this.$tooltip.innerWidth();var k=this.$tooltip.outerHeight(!1);if(this.$elProxy.is("area")){var l=this.$elProxy.attr("shape"),q=this.$elProxy.parent().attr("name"),p=d('img[usemap="#'+q+'"]'),q=p.offset().left,h=p.offset().top,r=void 0!==this.$elProxy.attr("coords")?this.$elProxy.attr("coords").split(","):void 0;if("circle"==l)l=parseInt(r[0]),
p=parseInt(r[1]),r=parseInt(r[2]),e.dimension.height=2*r,e.dimension.width=2*r,e.offset.top=h+p-r,e.offset.left=q+l-r;else if("rect"==l){var l=parseInt(r[0]),p=parseInt(r[1]),u=parseInt(r[2]),r=parseInt(r[3]);e.dimension.height=r-p;e.dimension.width=u-l;e.offset.top=h+p;e.offset.left=q+l}else if("poly"==l){for(var H=u=p=l=0,E="even",C=0;C<r.length;C++){var F=parseInt(r[C]);"even"==E?(F>u&&(u=F,0===C&&(l=u)),F<l&&(l=F),E="odd"):(F>H&&(H=F,1==C&&(p=H)),F<p&&(p=F),E="even")}e.dimension.height=H-p;e.dimension.width=
u-l;e.offset.top=h+p;e.offset.left=q+l}else e.dimension.height=p.outerHeight(!1),e.dimension.width=p.outerWidth(!1),e.offset.top=h,e.offset.left=q}var w=0,A=h=0,z=parseInt(this.options.offsetY),q=parseInt(this.options.offsetX),x=this.options.position;"top"==x&&(h=e.offset.left+g-(e.offset.left+e.dimension.width),w=e.offset.left+q-h/2,A=e.offset.top-k-z-12,b(),a("bottom","top"));"top-left"==x&&(w=e.offset.left+q,A=e.offset.top-k-z-12,b(),a("bottom-left","top-left"));"top-right"==x&&(w=e.offset.left+
e.dimension.width+q-g,A=e.offset.top-k-z-12,b(),a("bottom-right","top-right"));"bottom"==x&&(h=e.offset.left+g-(e.offset.left+e.dimension.width),w=e.offset.left-h/2+q,A=e.offset.top+e.dimension.height+z+12,b(),a("top","bottom"));"bottom-left"==x&&(w=e.offset.left+q,A=e.offset.top+e.dimension.height+z+12,b(),a("top-left","bottom-left"));"bottom-right"==x&&(w=e.offset.left+e.dimension.width+q-g,A=e.offset.top+e.dimension.height+z+12,b(),a("top-right","bottom-right"));"left"==x&&(w=e.offset.left-q-g-
12,h=e.offset.left+q+e.dimension.width+12,a=e.offset.top+k-(e.offset.top+e.dimension.height),A=e.offset.top-a/2-z,0>w&&h+g>f?(a=2*parseFloat(this.$tooltip.css("border-width")),b=g+w-a,this.$tooltip.css("width",b+"px"),k=this.$tooltip.outerHeight(!1),w=e.offset.left-q-b-12-a,a=e.offset.top+k-(e.offset.top+e.dimension.height),A=e.offset.top-a/2-z):0>w&&(w=e.offset.left+q+e.dimension.width+12,c="left"));"right"==x&&(w=e.offset.left+q+e.dimension.width+12,h=e.offset.left-q-g-12,a=e.offset.top+k-(e.offset.top+
e.dimension.height),A=e.offset.top-a/2-z,w+g>f&&0>h?(a=2*parseFloat(this.$tooltip.css("border-width")),this.$tooltip.css("width",f-w-a+"px"),k=this.$tooltip.outerHeight(!1),a=e.offset.top+k-(e.offset.top+e.dimension.height),A=e.offset.top-a/2-z):w+g>f&&(w=e.offset.left-q-g-12,c="right"));this.options.arrow&&(a="tooltipster-arrow-"+x,b=1>this.options.arrowColor.length?this.$tooltip.css("background-color"):this.options.arrowColor,c?"left"==c?(a="tooltipster-arrow-right",c=""):"right"==c?(a="tooltipster-arrow-left",
c=""):c="left:"+Math.round(c)+"px;":c="","top"==x||"top-left"==x||"top-right"==x?(q=parseFloat(this.$tooltip.css("border-bottom-width")),h=this.$tooltip.css("border-bottom-color")):"bottom"==x||"bottom-left"==x||"bottom-right"==x?(q=parseFloat(this.$tooltip.css("border-top-width")),h=this.$tooltip.css("border-top-color")):"left"==x?(q=parseFloat(this.$tooltip.css("border-right-width")),h=this.$tooltip.css("border-right-color")):"right"==x?(q=parseFloat(this.$tooltip.css("border-left-width")),h=this.$tooltip.css("border-left-color")):
(q=parseFloat(this.$tooltip.css("border-bottom-width")),h=this.$tooltip.css("border-bottom-color")),1<q&&q++,r="",0!==q&&(r="",h="border-color: "+h+";",-1!==a.indexOf("bottom")?r="margin-top: -"+Math.round(q)+"px;":-1!==a.indexOf("top")?r="margin-bottom: -"+Math.round(q)+"px;":-1!==a.indexOf("left")?r="margin-right: -"+Math.round(q)+"px;":-1!==a.indexOf("right")&&(r="margin-left: -"+Math.round(q)+"px;"),r='<span class="tooltipster-arrow-border" style="'+r+" "+h+';"></span>'),this.$tooltip.find(".tooltipster-arrow").remove(),
this.$tooltip.append('<div class="'+a+' tooltipster-arrow" style="'+c+'">'+r+'<span style="border-color:'+b+';"></span></div>'));this.$tooltip.css({top:Math.round(A)+"px",left:Math.round(w)+"px"})}return this},enable:function(){this.enabled=!0;return this},disable:function(){this.hide();this.enabled=!1;return this},destroy:function(){var a=this;a.hide();a.$el[0]!==a.$elProxy[0]&&a.$elProxy.remove();a.$el.removeData(a.namespace).off("."+a.namespace);var b=a.$el.data("tooltipster-ns");1===b.length?
(b=null,"previous"===a.options.restoration?b=a.$el.data("tooltipster-initialTitle"):"current"===a.options.restoration&&(b="string"===typeof a.Content?a.Content:d("<div></div>").append(a.Content).html()),b&&a.$el.attr("title",b),a.$el.removeClass("tooltipstered").removeData("tooltipster-ns").removeData("tooltipster-initialTitle")):(b=d.grep(b,function(b,c){return b!==a.namespace}),a.$el.data("tooltipster-ns",b));return a},elementIcon:function(){return this.$el[0]!==this.$elProxy[0]?this.$elProxy[0]:
void 0},elementTooltip:function(){return this.$tooltip?this.$tooltip[0]:void 0},option:function(a,b){if("undefined"==typeof b)return this.options[a];this.options[a]=b;return this},status:function(){return this.Status}};d.fn.tooltipster=function(){var a=arguments;if(0===this.length){if("string"===typeof a[0]){var b=!0;switch(a[0]){case "setDefaults":d.extend(c,a[1]);break;default:b=!1}return b?!0:this}return this}if("string"===typeof a[0]){var f="#*$~&";this.each(function(){var b=d(this).data("tooltipster-ns");
if(b=b?d(this).data(b[0]):null){if("function"===typeof b[a[0]])var c=b[a[0]](a[1],a[2]);else throw Error('Unknown method .tooltipster("'+a[0]+'")');if(c!==b)return f=c,!1}else throw Error("You called Tooltipster's \""+a[0]+'" method on an uninitialized element');});return"#*$~&"!==f?f:this}var k=[],e=(b=a[0]&&"undefined"!==typeof a[0].multiple)&&a[0].multiple||!b&&c.multiple,l=(b=a[0]&&"undefined"!==typeof a[0].debug)&&a[0].debug||!b&&c.debug;this.each(function(){var b=!1,c=d(this).data("tooltipster-ns"),
f=null;c?e?b=!0:l&&console.log('Tooltipster: one or more tooltips are already attached to this element: ignoring. Use the "multiple" option to attach more tooltips.'):b=!0;b&&(f=new g(this,a[0]),c||(c=[]),c.push(f.namespace),d(this).data("tooltipster-ns",c),d(this).data(f.namespace,f));k.push(f)});return e?k:this};var f=!!("ontouchstart"in n),u=!1;d("body").one("mousemove",function(){u=!0})})(jQuery,window,document);
$(document).ready(function(){jQuery(".modul.staff.members th").tooltipster({contentAsHTML:!0,animation:"grow",delay:40,speed:200,position:"bottom",theme:"tooltipster-theme"})});$(document).ready(function(){$(window).scroll(function(){150<$(this).scrollTop()?$(".scroll-to-top").fadeIn():$(".scroll-to-top").fadeOut()});$(".scroll-to-top").click(function(){$("html, body").animate({scrollTop:0},800);return!1})});$(document).ready(function(){$(".modul.subnav ul li:has(ul)").find("a:first").addClass("dropd")});